### ISSUE TITLE
Docker Image 

### ISSUE THREAD

**Issue by arr0n** [MediaBrowser/MediaBrowser.Build#27]
Hey guys,

Since a recent update i've found the the docker image to be a real drain on the CPU resource.  You're image has been working awesome for awhile, i've pulled the latest version and wow its really tanking the processor.  No other image is puling 120%-150%.  It seems to be one of the mono processes (mono /opt/mediabrowser/MediaBrowser.Server.Mono.exe -programdata /config -ffmpeg /usr/bin/ffmpeg -ffprobe /usr/bin/ffprobe) 

My docker version is;
Docker version 1.5.0

and its mediabrowser/mbserver:latest i'm using from the hub pulled today (22nd April)

**Comment by LukePulverenti** [comment]
Hi there. Newer releases nowadays will perform much better than from the time-frame this issue was opened. Please feel free to re-open if there is still an issue. Thanks.
