### ISSUE TITLE
Installing on RHEL 7 does not use the CentOS_7 Repo for MediaBrowserServer-Dependancies

### ISSUE THREAD

**Issue by robotmaxtron** [MediaBrowser/MediaBrowser.Build#30]
When performing a fresh installation on Red Hat Enterprise Linux 7, the repo is unable to be found and reports the following error:
failure: repodata/repomd.xml from MediaBrowserServer-Dependancies: [Errno 256] No more mirrors to try.
http://download.open...data/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

A fix for this would be to assume that both CentOS7 and RHEL7 share the same repository.

**Comment by LukePulverenti** [comment]
Hi there. You shouldn't see this anymore with our newer releases. Please feel free to re-open if there is still an issue. Thanks.
